name = "JuliaCore"
uuid = "12345678-1234-1234-1234-123456789012"
version = "0.1.0"
authors = ["Jin"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CatBoost = "e2e10f9a-a85d-4fa9-b6b2-639a32100a12"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
EvoTrees = "f6006082-12f8-11e9-0c9c-0d5d367ab1e5"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
SIRUS = "cdeec39e-fb35-4959-aadb-a1dd5dede958"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ArgParse = "1.2.0"
CUDA = "5.9.5"
CatBoost = "0.3.5"
Dates = "1.11.0"
DecisionTree = "0.12.4"
EvoTrees = "0.18.2"
Glob = "1.4.0"
Hyperopt = "0.5.6"
MLJ = "0.22.0"
Parquet2 = "0.2.33"
Printf = "1.11.0"
Random = "1.11.0"
SIRUS = "3.0.0"
Statistics = "1.11.1"
XGBoost = "2.5.2"
YAML = "0.4.16"
